version: "3.8"

volumes:
  portainer-data:
    name: "portainer-data"

services:
  portainer:
    container_name: portainer
    image: zuptalo/portainer:latest
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - portainer-data:/data/
      - /var/run/docker.sock:/var/run/docker.sock
